[package]
name = "web"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
common = { path = "../common" }
turso = { workspace = true }
topcoat = { workspace = true, features = ["router", "view", "tailwind"] }
serde = { workspace = true }

[build-dependencies]
topcoat = { workspace = true, features = ["tailwind"] }
